apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-link-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Link Management"
    rbac.authorization.halo.run/display-name: "友情链接查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:links:view"]
rules:
  - apiGroups: [ "" ]
    resources: [ "links" ]
    verbs: [ "get", "list" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-link-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Link Management"
    rbac.authorization.halo.run/display-name: "友情链接管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:links:manage"]
    rbac.authorization.halo.run/dependencies: |
      ["role-template-link-view"]
rules:
  - apiGroups: [ "" ]
    resources: [ "links" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
