apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-links-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          label: 页面标题
          name: title
          validation: required
          value: '链接'