apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-links-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          label: 页面标题
          name: title
          validation: required
          value: "链接"
    - group: verification
      label: 链接检测
      formSchema:
        - $formkit: checkbox
          label: 启用自动定时检测
          name: enabled
          id: verification_enabled
          value: false
          help: 启用后，系统会自动定时检测链接的可达性，并更新链接的可达性状态，如果关闭，可以在链接管理页面手动检测
        - $formkit: number
          if: "$get(verification_enabled).value === true"
          label: 检测间隔（小时）
          name: intervalHours
          validation: required|number|min:1
          value: 24
        - $formkit: number
          if: "$get(verification_enabled).value === true"
          label: 每轮最多检测链接数
          name: maxLinksPerRun
          validation: required|number|min:1
          value: 50
        - $formkit: checkbox
          if: "$get(verification_enabled).value === true"
          label: 同时检测反链
          name: checkBacklink
          value: false
    - group: rss
      label: RSS 订阅
      formSchema:
        - $formkit: checkbox
          label: 启用自动获取
          name: enabled
          id: rss_refresh_enabled
          value: true
          help: 启用后，系统会自动定时获取链接的 RSS 订阅，并更新链接的 RSS 订阅状态，如果关闭，可以在链接订阅页面手动获取
        - $formkit: number
          if: "$get(rss_refresh_enabled).value === true"
          label: 获取间隔（小时）
          name: intervalHours
          validation: required|number|min:1
          value: 1
        - $formkit: number
          if: "$get(rss_refresh_enabled).value === true"
          label: 每轮最多获取链接数
          name: maxLinksPerRun
          validation: required|number|min:1
          value: 50
        - $formkit: checkbox
          label: 公开 RSS 订阅动态
          name: publicEnabled
          value: false
          help: 部分主题可能需要显示 RSS 订阅信息，开启后匿名访问者和主题可以读取已抓取的 RSS 条目，请确认风险之后再决定是否开启
