apiVersion: v1alpha1
kind: Setting
metadata:
  name: links-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          help: This will be used for your account.
          label: Email
          name: email
          validation: required|email
        - $formkit: text
          label: 访问链接
          name: url
    - group: sns
      label: 社交资料
      formSchema:
        - $formkit: text
          help: This will be used for your theme.
          label: color
          name: color
          validation: required
        - $formkit: color
          help: This will be used for your theme.
          label: color
          name: color
          validation: required
